# ============================================
# TypeMasterAI - Google Cloud Build Configuration
# Alternative to GitHub Actions for GCP-native CI/CD
# ============================================
#
# Setup Instructions:
# 1. Create a Cloud Build trigger connected to your GitHub repo
# 2. Configure substitution variables in the trigger settings
# 3. Grant Cloud Run Admin and Service Account User roles to Cloud Build
#
# Trigger this build:
#   gcloud builds submit --config=cloudbuild.yaml .
# ============================================

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: typemasterai
  _REPOSITORY: typemasterai

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  substitutionOption: ALLOW_LOOSE

steps:
  # ============================================
  # Step 1: Build Docker Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '--cache-from=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '--build-arg=BUILDKIT_INLINE_CACHE=1'
      - '.'

  # ============================================
  # Step 2: Push to Artifact Registry
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
    waitFor: ['build']

  # ============================================
  # Step 3: Deploy to Cloud Run
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--port=8080'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--concurrency=80'
      - '--cpu-boost'
      - '--session-affinity'
      - '--no-cpu-throttling'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,SESSION_SECRET=SESSION_SECRET:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest'
    waitFor: ['push']

  # ============================================
  # Step 4: Verify Deployment Health
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')
        
        echo "Checking health at: $${SERVICE_URL}/api/health"
        
        for i in {1..24}; do
          RESPONSE=$$(curl -s -o /dev/null -w "%{http_code}" "$${SERVICE_URL}/api/health" || echo "000")
          if [ "$$RESPONSE" = "200" ]; then
            echo "✅ Health check passed!"
            exit 0
          fi
          echo "Attempt $$i: Status $$RESPONSE - waiting 5 seconds..."
          sleep 5
        done
        
        echo "❌ Health check failed after 2 minutes"
        exit 1
    waitFor: ['deploy']

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Build timeout (15 minutes)
timeout: '900s'

# Build tags for filtering in Cloud Build history
tags:
  - 'typemasterai'
  - 'cloud-run'
  - 'production'

